Remove useless XFree86 loader symbol lists
Removal of XFree86 loader and all of its long deprecated symbols.

Silences compiler warning:

ps3.c: In function ‘ps3Setup’:
ps3.c:189:3: warning: implicit declaration of function ‘LoaderRefSymLists’; did you mean ‘LoaderSymbol’? [-Wimplicit-function-declaration]
   LoaderRefSymLists(fbSymbols, exaSymbols, fbdevHWSymbols, NULL);
   ^~~~~~~~~~~~~~~~~
   LoaderSymbol
ps3.c: In function ‘PS3Probe’:
ps3.c:259:2: warning: implicit declaration of function ‘xf86LoaderReqSymLists’; did you mean ‘xf86LoaderCheckSymbol’? [-Wimplicit-function-declaration]
  xf86LoaderReqSymLists(fbdevHWSymbols, NULL);
  ^~~~~~~~~~~~~~~~~~~~~
  xf86LoaderCheckSymbol

Signed-off-by: Rhys Kidd <rhyskidd@gmail.com>