Include xorg-server.h (for driver) before including any <xorg/*.h>
Ensure xorg-server.h is included first, as it is at the top of config.h
This conditional inclusion is utilized widely amongst xorg drivers since
approximately 2014 to address this issue.

As explained by Daniel Stone:

 "Including anything from <xorg/*.h> without having either xorg-server.h
  (for drivers) or xorg-config.h (internal) included first results in
  undefined behaviour.

  Specifically on 64-bit systems, you lose out horrendously because CARD32
  secretly gets promoted via unsigned long to CARD64, as _XSERVER64 is not
  defined. The lack of all the functional definitions in xorg-server.h
  also means that your ABI's probably different even without the type
  differences.

  It's a terrible, terrible, idea that results in really hard-to-track-down
  bug reports."

See discussion: https://patchwork.freedesktop.org/patch/28957/

Error message avoided when building with X.org Server 1.20.1:

In file included from /usr/include/xorg/fb.h:37,
                 from /usr/include/xorg/exa.h:39,
                 from ps3_notifier.c:2:
/usr/include/xorg/servermd.h:51:2: error: #error Drivers must include xorg-server.h before any other xserver headers
 #error Drivers must include xorg-server.h before any other xserver headers
  ^~~~~
/usr/include/xorg/servermd.h:52:2: error: #error xserver code must include dix-config.h before any other headers
 #error xserver code must include dix-config.h before any other headers
  ^~~~~

Signed-off-by: Rhys Kidd <rhyskidd@gmail.com>